report_app/yds/report/urls.py
from django.urls import path
from . import views


app_name = "report"


urlpatterns = [
        # Home page.
        path('', views.index, name='index'),

        # About page.
        path('about/', views.about, name='about'),

        # ex : /Attiki/
        path('<str:a_region>/', views.selected_region, name='selected_region'),

        # ex : /Attiki/N. ANATOLIKIS ATTIKIS
        path('<str:a_region>/<str:a_municipality>/', views.selected_municipality, name='selected_municipality'),

        # ex: /Attiki/N. ANATOLIKIS ATTIKI/383752
        # path('<str:a_region>/<str:a_municipality>/<int:project_url_id>/', views.create_pdf, name='create_pdf'),

        # ex : /static/report/download/390273.pdf
        # path('static/report/download/<int:project_url_id>.pdf', views.create_pdf, name='create_pdf'),

        # ex : /pdf_error/Attiki/N. ANATOLIKIS ATTIKI/389383
        path('pdf_error/<str:a_region>/<str:a_municipality>/<int:project_url_id>/', views.pdf_error, name='pdf_error'),

        # ex : /ajax/create_pdf/389383
        path('ajax/create_pdf/<int:project_url_id>', views.create_pdf, name='create_pdf' ),

    ]

report_app/yds/yds/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),

    # For API application :
    path('api/', include('report_api.urls')),

    # Basic web application :
    path('', include('report.urls')),


]

report_app/yds/report/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage

from utilities.data_set import regions, municipality
from utilities.project import get_projects_by_municipality, get_project_data, search, generate_pdf, pdf_name

from os.path import dirname, abspath, join, getctime
from os import listdir, remove
from datetime import datetime, timedelta
import time
import threading



def index(request):
    """
    View που καλείται όταν ο χρήστης επισκεφτεί την αρχική σελίδα και θα πρέπει να επιλέξει μια περιφερειακή ενότητα.

    Δίνεται στη σελίδα :
    - Το λεξικό με όλες τις περιφερειακές ενότητες.
    - Την πρώτη περιφερειακή ενότητα ( στο λεξικό - για λόγους υλοποίησης στο action της φόρμας της σελίδας - ).

    :param request: Το αίτημα του χρήστη.
    :return: Την σελίδα «report/index.html» με τις παραπάνω πληροφορίες.
    """

    return render(request, 'report/index.html', {'regions': regions,
                                                 'first_region': list(regions.keys())[0]})




def about(request):
    """
    View που καλείται όταν ο χρήστης επισκεφτεί την σελίδα "Πληροφορίες".

    Απλώς επιστρέφει ένα στατικό HTML αρχείο.

    :param request: Το αίτημα του χρήστη.
    :return: Την σελίδα «report/about.html».
    """

    return render(request, 'report/about.html')




def selected_region(request, a_region):
    """
    View που καλείται όταν ο χρήστης έχει επιλέξει μια περιφερειακή ενότητα και θα πρέπει να επιλέξει ένα νομό.

    Δίνεται στην σελίδα  :
        - Η επιλεγμένη περιφερειακή ενότητα.
        - Το λεξικό με όλους τους νομούς της περιφερειακής ενότητας που επιλέχθηκε.
        - Τον πρώτο νομό ( στο λεξικό - για λόγους υλοποίησης στο action της φόρμας της σελίδας - ).

    :param request: Το αίτημα του χρήστη.
    :param a_region: Μια περιφερειακή ενότητα.
    :return: Την σελίδα με τις παραπάνω πληροφορίες.
    """

    try:
        if regions[a_region]:

            context = {'selected_region': a_region,
                       'first_municipality': list(municipality[a_region].keys())[0],
                       'municipalities': municipality[a_region]}

            return render(request, 'report/region.html', context)

    except KeyError:  # Αν δε βρει δηλαδή την περιφέρεια αυτή
        raise Http404("The region \"{0}\" was not found it!".format(a_region))




def selected_municipality(request, a_region, a_municipality):
    """
    View που καλείται όταν ο χρήστης έχει επιλέξει μια περιφερειακή ενότητα και νομό, και θα πρέπει να επιλέξει ένα έργο.

    Σε αυτή την σελίδα εμφανίζονται τα έργα που υπάρχουν για τον συγκεκριμένο νομό που έχει επιλεχθεί.
    Ο χρήστης μπορεί να επιλέξει κάποιο από αυτά τα έργα και να κατεβάσει μια PDF αναφορά για αυτό.

    Δίνεται στην σελίδα  :
        - Η επιλεγμένη περιφερειακή ενότητα.
        - Τον επιλεγμένο νομό της περιφερειακής ενότητας.
        - Όλα τα έργα του νομού.

    :param request: Το αίτημα του χρήστη.
    :param a_region: Μια περιφερειακή ενότητα.
    :param a_municipality: Ένας νομός της παραπάνω περιφερειακής ενότητας.
    :return: Την σελίδα με τις παραπάνω πληροφορίες.
    """

    try:
        if regions[a_region]:  # Αν υπάρχει η περιφέρεια μέσα στις περιφέρειες
            try:
                if municipality[a_region][a_municipality]:  # Αν υπάρχει ο νομός μέσα στη συγκεκριμένη περιφέρεια!

                    projects = get_projects_by_municipality(a_municipality)

                    # Διόρθωση του project url ώστε να παίρνω μονάχα το id του.
                    for name, url in projects.items():
                        projects[name] = url.split('/')[5]

                    context = {'selected_region': a_region,
                               'selected_municipality': a_municipality,
                               'projects': projects,
                               'total_number_of_projects': len(projects)}

                    return render(request, 'report/municipality.html', context)
            except KeyError:
                raise Http404("The municipality \"{0}\" was not found it!".format(a_municipality))
    except KeyError:
        raise Http404("The region \"{0}\" was not found it!".format(a_region))




def create_pdf(request, project_url_id):
    """
    Δημιουργία του εγγράφου αναφοράς.

    Η παρούσα συνάρτηση είναι υπεύθυνη ώστε να προσπαθήσει να δημιουργήσει ένα PDF έγγραφο αναφοράς για το έργο που θα
    της ζητηθεί και έπειτα να το επιστρέψει ένα μήνυμα επιτυχής παραγωγής του ή όχι.
    Αυτή η συνάρτηση καλείται μέσω AJAX.

    :param request: Το αίτημα του χρήστη.
    :param project_url_id: Το id του έργου ( όπως είναι στο «linkedeconomy.org» αλλά μονάχα το id του ).
    :return: Είτε το έγγραφο αναφοράς σε μορφή PDF με τα στοιχεία του έργου που δόθηκε ως παράμετρος, είτε "status=504"
             το οποίο σημαίνει πως για κάποιο λόγο δεν ήταν επιτυχής η παραγωγή του PDF.
    """

    url = "http://linkedeconomy.org/resource/PublicWork/" + str(project_url_id)
    file_name = str(project_url_id) + ".pdf"

    # To define the "STATIC_ROOT" path. ( Look at the "yds/settings.py" file. )
    base_dir = dirname( dirname(abspath(__file__)) )
    static_root = join(base_dir, "static/report/download/")

    # Downloading data from this project :
    project_data = get_project_data(url)

    # Search for related articles for this project :
    try:
        related_articles = search(project_data['title'])
    except:
        related_articles = {'Δεν ήταν δυνατή η εύρεση σχετικών δημοσιεύσεων.': '#'}


    # Delete olf PDFs:
    threading.Thread(target=delete_PDFs, args=(static_root,), kwargs={}, daemon=True).start()


    # Generating the report PDF for this project :
    try:
        generate_pdf(project_data, related_articles, pdf_name(static_root, url))
    except ValueError as log:
        print("Compiler error from LaTeX, for project : {0}".format(url))
        print('-------------------------------------------------------------------------------------------------------')
        print('LaTex Log |')
        print('-----------')
        print(log)
        print('-------------------------------------------------------------------------------------------------------')

        return HttpResponse(status=504)

    # Create success response :
    file_system = FileSystemStorage(static_root)
    with file_system.open(file_name) as pdf:

        # Create the HttpResponse object with the appropriate PDF headers.
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="' + file_name + '"'

        return response




def pdf_error(request, a_region, a_municipality, project_url_id):
    """
    Εμφάνιση μηνύματος σφάλματος για την παραγωγή ενός PDF.

    Όταν καλείται αυτή η συνάρτηση, τότε σημαίνει πως η παραγωγή ενός PDF δεν ήταν επιτυχής και αυτό το view αναλαμβάνει
    μονάχα να εμφανίσει μια σελίδα σφάλματα προς ενημέρωση του χρήστη.

    :param request: Το αίτημα του χρήστη.
    :param a_region: Σε ποια περιφερειακή ενότητα ανήκει το έργο που δεν ήταν εφικτή η παραγωγή του PDF.
    :param a_municipality: Σε ποιο νομό της παραπάνω περιφερειακής ενότητας ανήκει το έργο.
    :param project_url_id: Για ποιο έργο δεν ήταν εφικτή η παραγωγή του PDF.
    :return: Την σελίδα «report/pdf.html» με τις παραπάνω πληροφορίες.
    """

    context = {'region': a_region,
               'municipality': a_municipality,
               'project_id': project_url_id}

    return render(request, 'report/pdf.html', context)




def delete_PDFs( folder_path ):
    """
    Μέθοδος που αναλαμβάνει να διαγράψει όλα τα PDFs που πλέον θεωρούνται παλιά.

    Είναι μια πάρα πολύ σημαντική μέθοδος η οποία αναλαμβάνει να διαγράψει τα παλιά PDFs.
    Χωρίς αυτή ο αποθηκευτικός χώρος του διακομιστή κάποια στιγμή θα γέμιζε πλήρως και ο λόγος θα ήταν τα PDF.

    Αυτή η μέθοδος τρέχει παράλληλα κάθε φορά που εκτελείται η μέθοδος παραγωγής ενός νέου εγγράφου PDF.

    :param folder_path: Ο κατάλογος που αποθηκεύονται τα PDFs.
    :return: Θα πρέπει να έχουν διαγραφεί τα έργα που είναι παραπάνω από μια ώρα δημιουργημένα.
    """

    # Find PDF files.
    files = [ f for f in listdir(folder_path) ]

    # The time from an hour ago
    one_hour_before = datetime.now() + timedelta(hours=-1)

    # Delete older files
    for pdf in files:
        if datetime.strptime(time.ctime(getctime( folder_path + pdf )), "%a %b %d %H:%M:%S %Y") < one_hour_before:
            remove(folder_path + pdf)

report_app/yds/report/templates/report/about.html
{% extends "report/base-template.html" %}

{% block title %}
    YDS+R | Πληροφορίες
{% endblock %}


{% block content %}

        <div class="container mycontent">
            <p>
                Η εφαρμογή υλοποιήθηκε από τον <a href="https://github.com/Tas-sos" target="_blank">Λισγάρα Αναστάσιο</a> στο πλαίσιο του
                <a href="https://yourdatastories.eu/features/hackathons/yds-hackathon-athens/" target="_blank">YourDataStories Hackathon</a>
                που διοργανώθηκε στην Αθήνα στις 20 Οκτωβρίου 2017 στο πλαίσιο του ευρωπαϊκού έργου
                <a href="https://yourdatastories.eu/" target="_blank">YourDataStories</a>.
            </p>
        </div>

{% endblock %}

report_app/yds/report/templates/report/base-template.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="UTF-8">
        <meta name='keywords' content='pdf, public, project, diavgeia, yourdatastories, report, document'>
        <meta name='description' content='Generate report PDF document for a public project.'>
        <meta name='author' content='Tas-sos'>
        <meta name='designer' content='Tas-sos'>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>
            {% block title %}
            {% endblock %}
        </title>

        {% load staticfiles %}
        <link type="text/css" rel="stylesheet" href="{% static 'report/css/bootstrap.css'%}" />
        <link type="text/css" rel="stylesheet" href="{% static 'report/css/main.css'%}" />
        {% block extra_css %}
        {% endblock %}

    </head>
    <body>

        <header>
            <a href="{% url 'report:index' %}">
                <img src="{% static 'report/images/diavgeia-logo.png' %}" alt="Δι@ύγεια">  <div class="plus">+</div>
                <img src="{% static 'report/images/yds-logo.png' %}" alt="YDS">
            </a>

            <nav class="nav-bar">
                <a href="{% url 'report:index' %}">Έκδοση αναφοράς</a>
                <a href="{% url 'report:about' %}">Πληροφορίες</a>
                <a href="https://github.com/Tas-sos/yds-reports/" title="GitHub" target="_blank">Συνεισφορά</a>
            </nav>

        </header>


        <div class="container">
            <div class="row">
                <div class="col text-center">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>


        <script type="text/javascript" src="{% static 'report/js/jquery-3.2.1.min.js' %}"></script>
        {% block extra_js%}
        {% endblock %}

        <footer class=".panel-footer">
            <p class="text-muted">This platform has been developed in the context of <a href="https://yourdatastories.eu/features/hackathons/yds-hackathon-athens/" target="_blank">YDS Hackathon in Athens</a>
                by <a href="https://github.com/Tas-sos" target="_blank">Anastasio Lisgara</a>.</p>
        </footer>

    </body>
</html>

report_app/yds/report/templates/report/index.html
{% extends "report/base-template.html" %}

{% block title %}
    YDS+R | Έκδοση αναφοράς δημόσιου έργου
{% endblock %}


{% block content %}

    <h4> Επιλέξτε μια περιφέρεια. </h4>

    <form action="{% url 'report:selected_region' first_region %}" method="post" name="region_form" id="region_form">
        {% csrf_token %}

        <select name="selected_region" id="selected_region">
            {% for key, value in regions.items %}
                <option value="{{key}}">{{value}}</option>
            {% endfor %}
        </select>

        <br>

        <input type="submit" name="region_submit" id="region_submit" class="submit-button btn btn-info" value="Συνέχεια" />
    </form>

{% endblock %}


{% block extra_js %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'report/js/form_actions_region.js' %}"></script>
{% endblock %}

report_app/yds/report/templates/report/municipality.html
{% extends "report/base-template.html" %}

{% load extra_util_filters %}

{% block title %}
    YDS+R | {{selected_region|municipality_gr_name:selected_municipality}}
{% endblock %}

{% load staticfiles %}
{% block extra_css %}
    <link type="text/css" rel="stylesheet" href="{% static 'report/css/loading.css'%}" />
{% endblock %}

{% block content %}

    {% load staticfiles %}

    {% if selected_region %}

        <h4>
            <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
            <b>{{selected_region|region_gr_name}}</b>

        {% if selected_municipality %}

            <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
            <b>{{selected_region|municipality_gr_name:selected_municipality}}</b>
        </h4>
        <h4>
            <input type="text" name="keywords_field" class="keywords_field" id="keywords_field" placeholder="type keywords">
        </h4>
        <br>
        <p>Συνολικός αριθμός έργων : {{total_number_of_projects}}</p>
        <p id="founded"></p>

        <br>

        <div class="public-projects">
            {% for title, url in projects.items %}
                <div class="project">
                    <a href="{% static 'report/download/' %}{{url}}.pdf" title="Generate report PDF" target="_blank">{{title}}</a>
                    <hr>
                </div>
            {% endfor %}
        </div>

        {% endif %}
    {% endif %}

{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'report/js/search.js' %}"></script>
    <script type="text/javascript" src="{% static 'report/js/loading.js' %}"></script>
    <script type="text/javascript" src="{% static 'report/js/create_pdf_AJAX.js' %}"></script>
{% endblock %}

report_app/yds/report/templates/report/pdf.html
{% if project_id %}
<p>Failed to generate a PDF document for the project: <span style="color: red">{{project_id}}</span>
    belonging to the Municipality of <b>{{municipality}}</b>
    in the <b>{{region}}</b> region.</p>
    <p>Please report this issue in <b><a href="https://github.com/Tas-sos/yds-reports/issues"
                                      target="_blank"
                                      title="Report this failed request!">GitHub repository</a></b>
        indicating the <span style="color: red">project id</span> and in which
        <b>municipality</b> and
        <b>region</b> it is located!</p>
{% endif%}

report_app/yds/report/templates/report/region.html
{% extends "report/base-template.html" %}

{% load extra_util_filters %}


{% block title %}
    YDS+R | {{selected_region|region_gr_name}}
{% endblock %}


{% block content %}
    {% if selected_region %}

        <h3>{{selected_region|region_gr_name}}.</h3>
        <h4> Επιλέξτε τον νομό που επιθυμείτε. </h4>

        <form action="{% url 'report:selected_municipality' selected_region first_municipality %}" method="post" name="municipality_form" id="municipality_form">
            {% csrf_token %}

            <select name="selected_municipality" id="selected_municipality">
                {% for key, value in municipalities.items %}
                    <option value="{{key}}">{{value}}</option>
                {% endfor %}
            </select>

            <br>

            <input type="submit" name="municipality_submit" id="municipality_submit" class="submit-button btn btn-info" value="Συνέχεια"/>
        </form>

    {% endif %}

{% endblock %}


{% block extra_js %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'report/js/form_actions_municipality.js' %}"></script>
{% endblock %}